### ISSUE TITLE
启动Banner显示有bug

### ISSUE THREAD

**Issue by lgl2189** [pagehelper/Mybatis-PageHelper#857]
SpringBoot项目
有如下配置：
```yaml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  page-size-zero: true
```
使用以上配置，不出现Banner

![Image](https://github.com/user-attachments/assets/4115f48c-15b8-4472-a164-ec9db6242d98)

但是将mybatis的配置改为如下，添加log-impl后会出现banner
```yaml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
```
![Image](https://github.com/user-attachments/assets/1f288da8-11e4-4914-bb96-b3ff5d713aa2)
